/* HUSTLE: FROM NOTHING - stable GitHub Pages build */
(() => {
  'use strict';
  const SAVE_KEY='hustleFromNothing_v2';
  const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
  const defaultState=()=>({name:'Blayn',skin:'#b97a58',shirt:'#2563eb',pants:'#1e293b',hair:'#171717',cash:350,bank:0,rep:0,energy:100,hunger:100,day:1,hour:8,x:-55,z:70,jobsDone:0,totalEarned:0,selectedVehicle:null,vehicles:[],businesses:[],properties:[],skills:{drive:1,labor:1,clean:1,delivery:1,business:1}});
  let state=defaultState(),gameStarted=false,paused=false,activePanel=null,activeJob=null,jobTarget=null,keys={},threeLoaded=false,THREE=null,renderer=null,scene3d=null,camera=null,player=null,clock3d=null,interactables=[],worldGroup=null,npcGroup=null,lastTime=performance.now(),toastTimer=0;
  const jobs=[
    {id:'delivery',name:'Delivery Driver',desc:'Take a package across town.',pay:95,energy:15,skill:'delivery',rep:2,x:75,z:70},
    {id:'lawn',name:'Lawn Crew',desc:'Cut lawns for a neighborhood route.',pay:120,energy:20,skill:'labor',rep:3,x:-75,z:5},
    {id:'detail',name:'Mobile Detail',desc:'Clean a customer vehicle.',pay:150,energy:20,skill:'clean',rep:4,reqRep:1,x:75,z:5},
    {id:'warehouse',name:'Warehouse Shift',desc:'Sort pallets before the morning truck.',pay:180,energy:30,skill:'labor',rep:4,reqRep:2,x:75,z:-70}
  ];
  const vehicles=[
    {id:'bike',name:'Used Bike',price:650,speed:1.3},{id:'compact',name:'Old Compact',price:2200,speed:1.55},{id:'pickup',name:'Work Pickup',price:6200,speed:1.75},{id:'van',name:'Detail Van',price:11500,speed:1.65}
  ];
  const businesses=[
    {id:'mow',name:'Mow Squad',price:1400,income:125,req:5},{id:'shine',name:'Shine Lab',price:3400,income:280,req:12},{id:'wash',name:'Quick Wash',price:7500,income:650,req:25},{id:'mart',name:'Hustle Mart',price:22000,income:2100,req:50}
  ];
  const properties=[
    {id:'room',name:'Rent a Room',price:900,rep:3},{id:'apartment',name:'Starter Apartment',price:5800,rep:8},{id:'house',name:'Small House',price:18500,rep:18},{id:'luxury',name:'Hilltop Home',price:65000,rep:45}
  ];
  const money=n=>'$'+Math.round(Number(n)||0).toLocaleString();
  function toast(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),2200)}
  function save(silent=false){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));if(!silent)toast('Game saved.');updateHUD()}catch(e){console.error(e);toast('Save failed.')}}
  function loadSave(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return false;const s=JSON.parse(raw);state=Object.assign(defaultState(),s,{skills:Object.assign(defaultState().skills,s.skills||{})});return true}catch(e){console.error(e);return false}}
  function show(id){document.getElementById(id)?.classList.remove('hidden')} function hide(id){document.getElementById(id)?.classList.add('hidden')}
  function updateCreatorPreview(){const el=$('#previewAvatar');if(!el)return;const skin=$('#skinInput')?.value||'#b97a58',shirt=$('#shirtInput')?.value||'#2563eb',pants=$('#pantsInput')?.value||'#1e293b',hair=$('#hairInput')?.value||'#171717';el.innerHTML=`<div style="position:absolute;left:50%;top:26px;transform:translateX(-50%);width:62px;height:62px;border-radius:50%;background:${skin};box-shadow:inset 0 12px 0 ${hair}"></div><div style="position:absolute;left:50%;top:82px;transform:translateX(-50%);width:92px;height:92px;border-radius:18px;background:${shirt}"></div><div style="position:absolute;left:50%;top:172px;transform:translateX(-50%);width:78px;height:62px;border-radius:14px;background:${pants}"></div>`}
  function updateHUD(){[['#cash',money(state.cash)],['#bank',money(state.bank)],['#rep',state.rep],['#energy',Math.round(state.energy)],['#hunger',Math.round(state.hunger)+'%']].forEach(([s,v])=>{const el=$(s);if(el)el.textContent=v});}
  function closePanels(){['phonePanel','jobsPanel','businessPanel','inventoryPanel','vehiclePanel','propertyPanel','skillsPanel','mapPanel'].forEach(hide);activePanel=null}
  function openPanel(name){if(!name)return closePanels();closePanels();activePanel=name;const ids={phone:'phonePanel',jobs:'jobsPanel',business:'businessPanel',inventory:'inventoryPanel',vehicle:'vehiclePanel',property:'propertyPanel',skills:'skillsPanel',map:'mapPanel'};if(ids[name])show(ids[name]);renderPanel(name)}
  function renderPanel(n){if(n==='jobs')renderJobs();if(n==='business')renderBusinesses();if(n==='inventory')renderInventory();if(n==='vehicle')renderVehicles();if(n==='property')renderProperties();if(n==='skills')renderSkills();if(n==='map')drawBigMap()}
  function renderJobs(){const el=$('#jobsList');if(!el)return;el.innerHTML=jobs.map(j=>{const locked=state.rep<(j.reqRep||0),tired=state.energy<j.energy;return `<div class="list-row"><div><h3>${j.name}</h3><p>${j.desc}<br><span class="money">${money(j.pay)}</span> • ${j.energy}⚡ • +${j.rep} rep</p></div><button class="smallbtn" data-take-job="${j.id}" ${locked||tired?'disabled':''}>${locked?'LOCKED':tired?'TIRED':'TAKE JOB'}</button></div>`}).join('');$$('[data-take-job]').forEach(b=>b.onclick=()=>startJob(b.dataset.takeJob))}
  function startJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;if(state.energy<j.energy)return toast('You need more energy.');state.energy-=j.energy;activeJob=j;jobTarget={x:j.x,z:j.z};state.skills[j.skill]=(state.skills[j.skill]||1)+.15;closePanels();toast(`${j.name} started. Follow the yellow marker.`);updateMissionText()}
  function finishJob(){if(!activeJob)return;const j=activeJob,reward=j.pay+Math.floor((state.skills[j.skill]||1)*5);state.cash+=reward;state.totalEarned+=reward;state.rep+=j.rep;state.jobsDone++;activeJob=null;jobTarget=null;save(true);toast(`Job complete! +${money(reward)}.`);updateMissionText()}
  function renderBusinesses(){const el=$('#businessList');if(!el)return;el.innerHTML=businesses.map(b=>{const owned=state.businesses.includes(b.id),locked=state.rep<b.req;return `<div class="list-row"><div><h3>${b.name}</h3><p>${owned?'Owned • '+money(b.income)+'/day':money(b.price)+' • '+money(b.income)+'/day • requires '+b.req+' rep'}</p></div><button class="smallbtn" data-buy-business="${b.id}" ${owned||locked?'disabled':''}>${owned?'OWNED':locked?'LOCKED':'BUY'}</button></div>`}).join('');$$('[data-buy-business]').forEach(b=>b.onclick=()=>buyBusiness(b.dataset.buyBusiness))}
  function buyBusiness(id){const b=businesses.find(x=>x.id===id);if(!b||state.businesses.includes(id))return;if(state.rep<b.req)return toast('Build more reputation first.');if(state.cash<b.price)return toast('Not enough cash.');state.cash-=b.price;state.businesses.push(id);save(true);renderBusinesses();renderInventory();updateHUD();toast(`${b.name} is yours.`)}
  function renderInventory(){const el=$('#inventoryList');if(!el)return;const items=['📱 Phone','👕 Starter Outfit',...state.vehicles.map(id=>'🚗 '+(vehicles.find(v=>v.id===id)?.name||id)),...state.businesses.map(id=>'🏢 '+(businesses.find(b=>b.id===id)?.name||id)),...state.properties.map(id=>'🏠 '+(properties.find(p=>p.id===id)?.name||id))];el.innerHTML=items.map(i=>`<div class="statline"><span>${i}</span><b>OWNED</b></div>`).join('')}
  function renderVehicles(){const el=$('#vehicleList');if(!el)return;el.innerHTML=vehicles.map(v=>{const owned=state.vehicles.includes(v.id),active=state.selectedVehicle===v.id;return `<div class="list-row"><div><h3>${v.name}</h3><p>${owned?(active?'Currently equipped':'Owned'):money(v.price)+' • speed '+v.speed.toFixed(2)+'x'}</p></div><button class="smallbtn" data-vehicle="${v.id}" ${!owned&&state.cash<v.price?'disabled':''}>${active?'EQUIPPED':owned?'SELECT':'BUY'}</button></div>`}).join('');$$('[data-vehicle]').forEach(b=>b.onclick=()=>handleVehicle(b.dataset.vehicle))}
  function handleVehicle(id){const v=vehicles.find(x=>x.id===id);if(!v)return;if(!state.vehicles.includes(id)){if(state.cash<v.price)return toast('Not enough cash.');state.cash-=v.price;state.vehicles.push(id);state.selectedVehicle=id;toast(`${v.name} purchased.`)}else{state.selectedVehicle=id;toast(`${v.name} equipped.`)}save(true);renderVehicles();renderInventory();updateHUD()}
  function renderProperties(){const el=$('#propertyList');if(!el)return;el.innerHTML=properties.map(p=>{const owned=state.properties.includes(p.id);return `<div class="list-row"><div><h3>${p.name}</h3><p>${owned?'Owned • +'+p.rep+' rep':money(p.price)+' • +'+p.rep+' rep'}</p></div><button class="smallbtn" data-property="${p.id}" ${owned||state.cash<p.price?'disabled':''}>${owned?'OWNED':'BUY'}</button></div>`}).join('');$$('[data-property]').forEach(b=>b.onclick=()=>buyProperty(b.dataset.property))}
  function buyProperty(id){const p=properties.find(x=>x.id===id);if(!p||state.properties.includes(id))return;if(state.cash<p.price)return toast('Not enough cash.');state.cash-=p.price;state.properties.push(id);state.rep+=p.rep;save(true);renderProperties();renderInventory();updateHUD();toast(`${p.name} purchased.`)}
  function renderSkills(){const el=$('#skillsList');if(!el)return;el.innerHTML=Object.entries(state.skills).map(([k,v])=>`<div class="statline"><span>${k.charAt(0).toUpperCase()+k.slice(1)}</span><b>LV ${Math.floor(v)}</b></div>`).join('')+`<div class="statline"><span>Jobs completed</span><b>${state.jobsDone}</b></div><div class="statline"><span>Total earned</span><b>${money(state.totalEarned)}</b></div>`}
  function updateMissionText(){const t=$('#missionText'),p=$('#missionProgress');if(!t)return;if(activeJob&&jobTarget){const d=Math.hypot(state.x-jobTarget.x,state.z-jobTarget.z);t.textContent=`Go to the yellow job marker • ${Math.ceil(d)}m away.`;if(p)p.style.width=Math.max(0,Math.min(100,100-d/1.8))+'%'}else if(!state.vehicles.length){t.textContent='Get your first job, then buy your first vehicle.';if(p)p.style.width=Math.min(100,state.jobsDone*12)+'%'}else if(!state.businesses.length){t.textContent='Build reputation and save for your first business.';if(p)p.style.width=Math.min(100,state.rep*2)+'%'}else{t.textContent='Keep grinding. Own the city.';if(p)p.style.width='100%'}}
  function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.82,metalness:.03})}
  function addBuilding(x,z,w,d,h,c,label,kind){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));b.position.y=h/2;b.castShadow=true;b.receiveShadow=true;g.add(b);const roof=new THREE.Mesh(new THREE.BoxGeometry(w+.6,.5,d+.6),mat(0x0c1118));roof.position.y=h+.25;g.add(roof);g.position.set(x,0,z);worldGroup.add(g);interactables.push({x,z,label,kind})}
  function buildPlayer(){if(player)scene3d.remove(player);player=new THREE.Group();player.position.set(state.x,0,state.z);scene3d.add(player);const lm=mat(state.pants),sm=mat(state.shirt),skin=mat(state.skin),hair=mat(state.hair);const l=new THREE.Mesh(new THREE.BoxGeometry(.42,.9,.42),lm);l.position.set(-.25,.45,0);const r=l.clone();r.position.x=.25;const body=new THREE.Mesh(new THREE.BoxGeometry(1.05,1.2,.6),sm);body.position.y=1.45;const head=new THREE.Mesh(new THREE.SphereGeometry(.48,16,12),skin);head.position.y=2.35;const h=new THREE.Mesh(new THREE.SphereGeometry(.5,16,8,0,Math.PI*2,0,Math.PI/2),hair);h.position.y=2.57;player.add(l,r,body,head,h);player.traverse(o=>{if(o.isMesh)o.castShadow=true})}
  function initThree(){if(!threeLoaded||renderer)return;const canvas=$('#scene');if(!canvas)return;try{scene3d=new THREE.Scene();scene3d.background=new THREE.Color(0x8fb4d5);scene3d.fog=new THREE.Fog(0x8fb4d5,90,320);camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,700);camera.position.set(-62,8,62);renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;clock3d=new THREE.Clock();scene3d.add(new THREE.HemisphereLight(0xdff1ff,0x25352c,2));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(-80,130,80);sun.castShadow=true;scene3d.add(sun);worldGroup=new THREE.Group();scene3d.add(worldGroup);npcGroup=new THREE.Group();scene3d.add(npcGroup);const ground=new THREE.Mesh(new THREE.BoxGeometry(220,.5,220),mat(0x40553d));ground.position.y=-.35;ground.receiveShadow=true;worldGroup.add(ground);for(let i=-100;i<=100;i+=40){const a=new THREE.Mesh(new THREE.BoxGeometry(12,.08,220),mat(0x1f252a));a.position.set(i,.02,0);worldGroup.add(a);const b=new THREE.Mesh(new THREE.BoxGeometry(220,.08,12),mat(0x1f252a));b.position.set(0,.03,i);worldGroup.add(b)}addBuilding(-55,70,20,16,11,0x253246,'JOB CENTER','job');addBuilding(55,70,22,16,13,0x3c2d2d,'DEALER','vehicle');addBuilding(-55,-70,22,16,10,0x293f4a,'BANK','bank');addBuilding(55,-70,24,18,12,0x4c3d27,'REALTY','property');addBuilding(0,-5,28,22,17,0x26404a,'BUSINESS HUB','business');for(let i=0;i<12;i++){const n=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(.65,1.15,.42),mat([0x334155,0x7c3aed,0x15803d,0xb45309][i%4]));body.position.y=.75;const head=new THREE.Mesh(new THREE.SphereGeometry(.3,12,10),mat([0xc08457,0x7b4b35,0xe2ad84][i%3]));head.position.y=1.55;n.add(body,head);n.position.set(-90+(i*23)%180,-80+(i*31)%160);n.userData.phase=i;npcGroup.add(n)}buildPlayer();requestAnimationFrame(loop)}catch(e){console.error(e);toast('3D graphics failed; refresh and try again.')}}
  function nearest(){let best=null,bd=9999;for(const i of interactables){const d=Math.hypot(state.x-i.x,state.z-i.z);if(d<bd){bd=d;best=i}}return bd<9?best:null}
  function interact(){if(!gameStarted||activePanel)return;const n=nearest();if(!n)return toast('Nothing close enough.');if(n.kind==='job')openPanel('jobs');else if(n.kind==='vehicle')openPanel('vehicle');else if(n.kind==='bank'){if(state.cash<=0)return toast('No cash to deposit.');const a=Math.floor(state.cash*.5);state.cash-=a;state.bank+=a;save();toast(`Deposited ${money(a)}.`)}else if(n.kind==='property')openPanel('property');else if(n.kind==='business')openPanel('business')}
  function move(dt){if(!gameStarted||paused||activePanel)return;let dx=0,dz=0;if(keys.KeyW||keys.ArrowUp)dz--;if(keys.KeyS||keys.ArrowDown)dz++;if(keys.KeyA||keys.ArrowLeft)dx--;if(keys.KeyD||keys.ArrowRight)dx++;if(!dx&&!dz)return;const len=Math.hypot(dx,dz);dx/=len;dz/=len;const v=vehicles.find(x=>x.id===state.selectedVehicle);const speed=(v?8*v.speed:7)*((keys.ShiftLeft||keys.ShiftRight)?1.45:1);state.x=Math.max(-104,Math.min(104,state.x+dx*speed*dt));state.z=Math.max(-104,Math.min(104,state.z+dz*speed*dt));state.hunger=Math.max(0,state.hunger-dt*.35);if(keys.ShiftLeft||keys.ShiftRight)state.energy=Math.max(0,state.energy-dt*10);if(player){player.position.set(state.x,0,state.z);player.rotation.y=Math.atan2(dx,dz)}if(jobTarget&&activeJob&&Math.hypot(state.x-jobTarget.x,state.z-jobTarget.z)<7)finishJob()}
  function updateCamera(){if(!camera||!player)return;const target=new THREE.Vector3(state.x,1.5,state.z),behind=new THREE.Vector3(Math.sin(player.rotation.y)*7,4.6,Math.cos(player.rotation.y)*7);camera.position.lerp(target.clone().add(behind),.09);camera.lookAt(target)}
  function updatePrompt(){const p=$('#prompt');if(!p)return;if(activePanel){p.classList.add('hidden');return}const n=nearest();if(!n){p.classList.add('hidden');return}p.textContent=`PRESS E — ${n.label}`;p.classList.remove('hidden')}
  function drawMinimap(){const c=$('#minimap');if(!c)return;const d=devicePixelRatio||1,w=c.clientWidth||220,h=c.clientHeight||220;c.width=w*d;c.height=h*d;const x=dctx=>dctx/220;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#101820';ctx.fillRect(0,0,c.width,c.height);const sx=v=>c.width/2+v*x(c.width),sz=v=>c.height/2+v*x(c.height);ctx.strokeStyle='#323b45';ctx.lineWidth=8*d;for(let i=-100;i<=100;i+=40){ctx.beginPath();ctx.moveTo(sx(i),0);ctx.lineTo(sx(i),c.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,sz(i));ctx.lineTo(c.width,sz(i));ctx.stroke()}[[ -55,70,'#3b82f6'],[55,70,'#f59e0b'],[-55,-70,'#22c55e'],[55,-70,'#a78bfa'],[0,-5,'#ec4899']].forEach(([xx,zz,col])=>{ctx.fillStyle=col;ctx.beginPath();ctx.arc(sx(xx),sz(zz),5*d,0,Math.PI*2);ctx.fill()});if(jobTarget){ctx.fillStyle='#facc15';ctx.beginPath();ctx.arc(sx(jobTarget.x),sz(jobTarget.z),6*d,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(sx(state.x),sz(state.z),5*d,0,Math.PI*2);ctx.fill()}
  function drawBigMap(){const c=$('#bigMap');if(!c)return;const ctx=c.getContext('2d'),w=c.width,h=c.height,sx=v=>w/2+v/220*w,sz=v=>h/2+v/220*h;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b1118';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#2d3640';ctx.lineWidth=22;for(let i=-100;i<=100;i+=40){ctx.beginPath();ctx.moveTo(sx(i),0);ctx.lineTo(sx(i),h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,sz(i));ctx.lineTo(w,sz(i));ctx.stroke()}[['JOB',-55,70,'#3b82f6'],['DEALER',55,70,'#f59e0b'],['BANK',-55,-70,'#22c55e'],['REALTY',55,-70,'#a78bfa'],['BUSINESS',0,-5,'#ec4899']].forEach(([lab,x,z,col])=>{ctx.fillStyle=col;ctx.beginPath();ctx.arc(sx(x),sz(z),9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 15px system-ui';ctx.textAlign='center';ctx.fillText(lab,sx(x),sz(z)-14)});if(jobTarget){ctx.fillStyle='#facc15';ctx.beginPath();ctx.arc(sx(jobTarget.x),sz(jobTarget.z),11,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(sx(state.x),sz(state.z),9,0,Math.PI*2);ctx.fill()}
  function loop(now){const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;move(dt);updatePrompt();updateHUD();updateMissionText();drawMinimap();if(renderer&&!paused){updateCamera();renderer.render(scene3d,camera)}requestAnimationFrame(loop)}
  function enterGame(){gameStarted=true;paused=false;closePanels();hide('boot');hide('creator');show('gameUI');updateHUD();updateMissionText();loadThree();toast(`Welcome, ${state.name}.`)}
  function loadThree(){if(threeLoaded||document.getElementById('three-cdn'))return;const s=document.createElement('script');s.id='three-cdn';s.src='https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.min.js';s.onload=()=>{THREE=window.THREE;threeLoaded=true;initThree()};s.onerror=()=>toast('3D engine failed to load. Menus still work; refresh to retry.');document.head.appendChild(s)}
  function bind(){
    $('#startBtn')?.addEventListener('click',()=>{hide('boot');show('creator')});
    $('#continueBtn')?.addEventListener('click',()=>{if(loadSave())enterGame();else toast('No saved game yet.')});
    $('#createBtn')?.addEventListener('click',()=>{state=defaultState();state.name=$('#nameInput')?.value.trim()||'Blayn';state.skin=$('#skinInput')?.value||state.skin;state.shirt=$('#shirtInput')?.value||state.shirt;state.pants=$('#pantsInput')?.value||state.pants;state.hair=$('#hairInput')?.value||state.hair;localStorage.removeItem(SAVE_KEY);enterGame()});
    $('#saveBtn')?.addEventListener('click',()=>save());$('#pauseBtn')?.addEventListener('click',()=>{paused=!paused;paused?show('pausePanel'):hide('pausePanel')});$('#resumeBtn')?.addEventListener('click',()=>{paused=false;hide('pausePanel')});$('#restartBtn')?.addEventListener('click',()=>{localStorage.removeItem(SAVE_KEY);location.reload()});
    $$('[data-panel]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));$$('.closePanel').forEach(b=>b.addEventListener('click',closePanels));
    ['skinInput','shirtInput','pantsInput','hairInput'].forEach(id=>$('#'+id)?.addEventListener('input',updateCreatorPreview));
    window.addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='KeyE')interact();if(e.code==='KeyP')openPanel(activePanel==='phone'?null:'phone');if(e.code==='KeyM')openPanel(activePanel==='map'?null:'map');if(e.code==='Escape'){if(activePanel)closePanels();else if(gameStarted){paused=!paused;paused?show('pausePanel'):hide('pausePanel')}}});
    window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('beforeunload',()=>save(true));window.addEventListener('resize',()=>{if(camera&&renderer){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}drawMinimap()});
  }
  function boot(){bind();updateCreatorPreview();updateHUD();hide('creator');hide('gameUI');show('boot')}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
